### ISSUE TITLE
known_content_type behaviour doesn't match the documentation

### ISSUE THREAD

**Issue by robrwo** [houseabsolute/webmachine-perl#27]
The docs for Web::Machine::Resource for `known_content_type` state:

> The value of $content_type is derived from the Plack::Request object and will therefore be an instance of the HTTP::Headers::ActionPack::MediaType class.

but `$content_type` appears to be a string, with Plack::Request 1.0033.

**Comment by autarch** [comment]
This is a bug. I will fix it in the next release.

**Comment by autarch** [comment]
Fixed in the latest release.
